repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.68.1 # v.1.63.0 and above require bash 5 from brew
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_docs # Update our output, if updates it will force a failure which is good
        args:
          - "--args=-c .config/.terraform-docs.yml"
      - id: terraform_docs # Verify out output is up to date, sometimes the update fails
        always_run: true
        args:
          - "--args=--output-check=true"
      - id: terrascan
        args:
          - "--args=-c .config/terrascan.yaml"
          - "--args=--non-recursive"
          - "--args=-i terraform" #If we don't specify this it came back with Docker failures and produces a non zero exit code
      - id: terraform_tflint
        args:
          - "--args=--only=terraform_deprecated_interpolation"
          - "--args=--only=terraform_deprecated_index"
          - "--args=--only=terraform_unused_declarations"
          - "--args=--only=terraform_comment_syntax"
          - "--args=--only=terraform_documented_outputs"
          - "--args=--only=terraform_documented_variables"
          - "--args=--only=terraform_typed_variables"
          - "--args=--only=terraform_module_pinned_source"
          - "--args=--only=terraform_naming_convention"
          #- '--args=--only=terraform_required_version' # This is bugged with the new Terraform provider syntax
          - "--args=--only=terraform_required_providers"
          - "--args=--only=terraform_workspace_remote"
      - id: terraform_tfsec
        args:
          - "--args=--exclude-downloaded-modules"
          - "--args=--concise-output"
  # Native Git PreCommit Hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: no-commit-to-branch
        args: [--branch, main, --branch, master]
  #GitLeaks
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.2.0
    hooks:
      - id: gitleaks
  #Prettier
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2
    hooks:
      - id: prettier
